all: program1 program2 program3 program4

clean:
	rm -f program1 program2 program3 program4 

program1: program1.c
	gcc -o program1 program1.c -Wall 

program2: program2.c 
	gcc -o program2 program2.c -Wall

program3: program3.c
	gcc -o program3 program3.c -Wall

program4: program4.c
	gcc -o program4 program4.c -Wall
